RentalMobil/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import multiprocessing

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/pdf/', views.generate_pdf, name="generate_pdf"),
    path('contact/', views.Contact, name="contact"),
    path('mobil/', include(('mobil.urls', 'mobil'), namespace='mobil')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('pesanan/', include(('pesanan.urls', 'pesanan'), namespace="pesanan")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobil/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list-car/', views.listCar, name="listCar"),
    path('detail-car/<int:mobil_id>', views.detailCar, name="detailCar"),
    
    path('master-mobil/', views.masterMobil, name="masterMobil"),
    path('create-mobil/', views.createMobil, name="createMobil"),
    path('update-mobil/<int:id>', views.updateMobil, name="updateMobil"),
    path('delete-mobil/<int:id>', views.deleteMobil, name="deleteMobil")
]

pesanan/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('form-checkout/<int:mobil_id>', views.formCheckout, name="formCheckout"),
    path('set-rental-dates/<int:mobil_id>', views.setRentalDates, name='setRentalDates'),
    path('my-order/', views.MyOrder, name="MyOrder"),
    path('return-order/<int:id_order>', views.returnOrder, name="returnOrder"),
    
    path('manage-order/', views.manageOrder, name="manageOrder"),
    path('update_status/<int:id_order>', views.updateStatus, name="updateStatus"),
    path('feedback-order/', views.feedbackOrder, name="feedbackOrder"),
    path('updateStatusFeedbackOrder/<int:id_order>', views.updateStatusFeedbackOrder, name="updateStatusFeedbackOrder")
]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login-admin/', views.loginAdmin, name="loginAdmin"),
    path('login-user/', views.loginUser, name="loginUser"),
    path('register-user/', views.registerUser, name="registerUser"),
    path('logout/', views.logout, name="logout")
]

templates/partials/navbarAdmin.html
<nav class="navbar navbar-expand-lg bg-body-tertiary rounded fixed-top nav-admin bg-light" aria-label="Thirteenth navbar example">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div style="padding: 5px;" class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
      <a class="navbar-brand col-lg-3 me-0 fw-bold shadow-none" href="{% url 'dashboard' %}">RENTCAR</a>
      <ul class="navbar-nav col-lg-9 justify-content-lg-end" >
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mobil:masterMobil' %}">Master Mobil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pesanan:manageOrder' %}">Master Order</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pesanan:feedbackOrder' %}">Master FeedBack</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn-logout" href="{% url 'user:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket text-danger"></i></a>
        </li>
        
        
      </ul>

    </div>
  </div>
</nav>

templates/partials/navbarUser.html
<nav class="navbar navbar-expand-lg bg-body-tertiary rounded fixed-top bg-light" aria-label="Thirteenth navbar example">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div style="padding: 5px;" class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
      <a class="navbar-brand col-lg-3 me-0 fw-bold shadow-none" href="{% url 'home' %}">RENTCAR</a>
      <ul class="navbar-nav col-lg-9 justify-content-lg-end" >
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mobil:listCar' %}">List Car</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown shadow-none ml-3">
          <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hi, {{current_user.username}}
          </a>
          <ul class="dropdown-menu"  aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item " href="{% url 'pesanan:MyOrder' %}">My Order</a></li>
            <li><a class="dropdown-item" href="{% url 'user:logout' %}">logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a  href="{% url 'user:loginUser' %}" class="btn btn-login shadow-none" type="button">login</a>
        </li>
        {% endif %}
        
      </ul>

    </div>
  </div>
</nav>