RentalMobil/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import multiprocessing

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/pdf/', views.generate_pdf, name="generate_pdf"),
    path('contact/', views.Contact, name="contact"),
    path('mobil/', include(('mobil.urls', 'mobil'), namespace='mobil')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('pesanan/', include(('pesanan.urls', 'pesanan'), namespace="pesanan")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobil/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list-car/', views.listCar, name="listCar"),
    path('detail-car/<int:mobil_id>', views.detailCar, name="detailCar"),
    
    path('master-mobil/', views.masterMobil, name="masterMobil"),
    path('create-mobil/', views.createMobil, name="createMobil"),
    path('update-mobil/<int:id>', views.updateMobil, name="updateMobil"),
    path('delete-mobil/<int:id>', views.deleteMobil, name="deleteMobil")
]

pesanan/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('form-checkout/<int:mobil_id>', views.formCheckout, name="formCheckout"),
    path('set-rental-dates/<int:mobil_id>', views.setRentalDates, name='setRentalDates'),
    path('my-order/', views.MyOrder, name="MyOrder"),
    path('return-order/<int:id_order>', views.returnOrder, name="returnOrder"),
    
    path('manage-order/', views.manageOrder, name="manageOrder"),
    path('update_status/<int:id_order>', views.updateStatus, name="updateStatus"),
    path('feedback-order/', views.feedbackOrder, name="feedbackOrder"),
    path('updateStatusFeedbackOrder/<int:id_order>', views.updateStatusFeedbackOrder, name="updateStatusFeedbackOrder")
]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login-admin/', views.loginAdmin, name="loginAdmin"),
    path('login-user/', views.loginUser, name="loginUser"),
    path('register-user/', views.registerUser, name="registerUser"),
    path('logout/', views.logout, name="logout")
]

pesanan/models.py
from django.db import models
from django.utils import timezone
from user.models import User
from mobil.models import Mobils

class Order(models.Model):
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    grand_total = models.BigIntegerField()
    STATUS_CHOICES = (
        ("Belum Terkonfirmasi", "Belum Terkonfirmasi"),
        ("Terkonfirmasi", "Terkonfirmasi"),
        ("Dikirim", "Dikirim"),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    payment_receipt_image_path = models.ImageField(upload_to="images/")
    photo_kk = models.ImageField(upload_to="images/")
    photo_ktp = models.ImageField(upload_to="images/")
    telephone = models.IntegerField()
    address = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    fine = models.BigIntegerField(default=0)

    def hitung_fine(self):
        if self.status == 'Dikirim' and self.end_date < timezone.now().date():
            hari_keterlambatan = (timezone.now().date() - self.end_date).days
            self.fine = (self.grand_total * 0.02) * hari_keterlambatan if hari_keterlambatan > 0 else 0
        else:
            self.fine = 0

    def save(self, *args, **kwargs):
        self.hitung_fine()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Order with id : {self.id}"

class OrderItem(models.Model):
    id_order = models.ForeignKey(Order, on_delete=models.CASCADE)
    id_mobils = models.ForeignKey(Mobils, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class ReturnOrder(models.Model):
    id_order = models.ForeignKey(Order, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/")
    photo_payment_fine = models.ImageField(upload_to='images/', null=True, blank=True)
    STATUS_CHOICES = [
        ('Dikembalikan', 'Dikembalikan'),
        ('Diterima', 'Diterima'),
    ]
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Dikembalikan')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def save(self, *args, **kwargs):
        if self.id_order.fine > 0:
            if not self.photo_payment_fine:
                raise ValueError("Foto pembayaran denda wajib diunggah untuk pengembalian terlambat")
        super().save(*args, **kwargs)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

ADMIN = "Admin"
USER = "User"

class User(AbstractUser):
    role_list = (
        (ADMIN, 'Admin'),
        (USER, 'User')
    )
    
    email = models.EmailField(max_length=255, unique=True)  # Set max_length to 255 and make email unique
    username = models.CharField(max_length=50, unique=True)
    role = models.CharField(max_length=100, choices=role_list, default=USER)
    text_password = models.CharField(max_length=100, blank=True, null=True)
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    def __str__(self):
        return self.email

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as login_user, logout as logout_user
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password

from .models import User

# Create your views here.
def loginAdmin(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        if not username or not password:
            messages.error(request, 'Username and Password Cannot be Empty ')
            return redirect('user:loginAdmin')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_superuser:
                login_user(request, user)
                print('masuk admin')
                return redirect('dashboard')
            else:
                messages.error(request, 'You do not have admin privileges.')
                print("Kamu bukan admin")
        else:
            print("error user")
            messages.error(request, 'Invalid username or password.')

    return render(request, 'admin/loginAdmin.html')

def loginUser(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        if not email or not password:
            messages.error(request, 'Email and Password Cannot be Empty ')
            return redirect('user:loginUser')
        
        try:
            # Retrieve the user by email
            user = User.objects.get(email=email)
            # Authenticate using the username and password
            authenticated_user = authenticate(request, username=user.username, password=password)
            
            if authenticated_user is not None:
                if authenticated_user.role == "User":
                    login_user(request, authenticated_user)
                    messages.success(request, 'Success login')
                    return redirect('home')
                else:
                    print('Invalid credentials')
                    messages.error(request, 'Invalid Credentials.')
            else:
                print('Invalid email or password')
                messages.error(request, 'Invalid email or password.')
        except User.DoesNotExist:
            messages.error(request, 'Invalid email or password.')
            print('Invalid email or password')
        except Exception as e:
            print('Error occurred: {e}')
        
    return render(request, 'user/loginUser.html')

def registerUser(request):
    if request.method == "POST":
        firstName = request.POST.get("firstName")
        lastName = request.POST.get("lastName")
        email = request.POST.get("email")
        password = request.POST.get("password")
        hash_password = make_password(password)
        
        if not firstName or not lastName or not email or not password:
            messages.error(request, 'Form Cannot be Empty ')
            return redirect('user:registerUser')
        
        try:
            # Check if email already exists
            if User.objects.filter(email=email).exists():
                messages.error(request, 'Email is already registered.')
                return render(request, 'user/registerUser.html')

            user = User.objects.create(
                username=firstName +" "+lastName,
                email=email,
                password=hash_password,
                text_password=password,
                role="User"
            )
            
            # Authenticate and login the user
            authenticated_user = authenticate(username=user.username, password=password)
            if authenticated_user is not None:
                login_user(request, authenticated_user)
                messages.success(request, 'Registration successful and you are now logged in')
                return redirect('home')
            else:
                messages.error(request, 'Authentication failed. Please try again.')
        except Exception as e:
            messages.error(request, f'Error occurred: {e}')
        
    return render(request, 'user/registerUser.html')

def logout(request):
    current_user = request.user.role if request.user.is_authenticated else None
    logout_user(request)
    if current_user is not None and current_user == "User":
        messages.success(request, 'Berhasil Logout!!')
        return redirect('home')
    else:
        return redirect('user:loginAdmin')

templates/user/contact.html
{% extends '../base.html' %}
{% load static %}
{% block headers %}
<link rel="stylesheet" href="{% static 'css/user/contact.css' %}">
{% endblock headers %}

{% block contents %}
{% include '../partials/navbarUser.html' %}

<main class="container " style="margin-top: 7%">
    <div class="container py-5 mt-5">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="contact-info">
              <h2 class="text-center mb-4">Hubungi Kami</h2>
              <ul class="list-group">
                <li class="list-group-item">Email: example@example.com</li>
                <li class="list-group-item">Phone: +123456789</li>
                <li class="list-group-item">Address: 123 Street, City, Country</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
</main>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3  border-top w-100">
    <div class="col text-start" style="color: white; font-weight:700; font-size: 13px">
      <a href="" class="mb-3 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="40" height="24">
          <use xlink:href="#bootstrap" />
        </svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">&copy; RentCar</span>
    </div>
    <div class="col-md-4 text-end mr-3">
      <img src="{% static 'img/wa.png' %}" alt="" width="23px">
      <img src="{% static 'img/instagram.png' %}" alt="" width="23px">
      <img src="{% static 'img/facebook.png' %}" alt="" width="23px">
    </div>
  </footer>

<script>
    const ratings = document.getElementById('rating1'); const rating1 = new CDB.Rating(ratings);
    rating1.getRating;
</script>
{% endblock contents %}

templates/user/detailCar.html
{% extends '../base.html' %}
{% load static %}
{% block headers %}
<link href="{% static 'css/user/detailCar.css' %}" rel="stylesheet" type="text/css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock headers %}

{% block contents %}
{% include '../partials/navbarUser.html' %}
<main class="wrapper" style="margin-top:5%">
  {% include 'widgets/flasher.html' %}
  <div class="row">
    <div class="col-md-9 mb-3">
      <div id="productCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{ mobils.image1.url }}" class="d-block w-100" alt="Product Image 1">
          </div>
          <div class="carousel-item">
            <img src="{{ mobils.image2.url }}" class="d-block w-100" alt="Product Image 2">
          </div>
          <div class="carousel-item">
            <img src="{{ mobils.image3.url }}" class="d-block w-100" alt="Product Image 3">
          </div>
        </div>
      </div>
      <div class="dot-container">
        <div class="dot active"></div>
        <div class="dot"></div>
        <div class="dot"></div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="row justify-content-between">
        <div class="col-7">
          <div class="nameCar">{{mobils.name}}</div>
        </div>
        <div class="col-4 text-right">
          <label class="text-warning starate">★</label> {{ average_rating }}
        </div>
      </div>
      <div class="price">{{mobils.pricePerDay}} /hari</div>

      <div class="description">{{mobils.description}}</div>
      <div class="stock">
        <div class="header">Seat</div> {{mobils.seat}}
      </div>
      <div class="transmission">
        <div class="header">Transmission</div> {{mobils.transmission}}
      </div>
      <div class="transmission">
        <div class="header">Stock</div> {{mobils.stock}}
      </div>
      <div class="type">
        <div class="header">Type</div>{{mobils.typeCar}}
      </div>
      <form method="POST" action="{% url 'pesanan:setRentalDates' mobil_id=mobils.id %}">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
            <div class="mb-2 form-group">
              <label for="checkIn" class="form-label">Check In</label>
              <input type="date" class="form-control shadow-none" id="checkIn" name="checkIn">
            </div>
          </div>
          <div class="col-md-6">
            <div class="mb-2 form-group">
              <label for="checkOut" class="form-label">Check Out</label>
              <input type="date" class="form-control shadow-none" id="checkOut" name="checkOut">
            </div>
          </div>
        </div>
        <div class="mb-2 form-group">
          <label for="quantity" class="form-label">Quantity</label>
          <input type="number" class="form-control shadow-none" id="quantity" name="quantity" placeholder="Quantity">
        </div>
        {% if mobils.stock != 0 %}
        <button class="btn shadow-none book-nows align-self-end" type="submit">
          Book</button>
        {% else %}
        <button class="btn shadow-none book-nows align-self-end disabled" type="submit">
          Book</button>
        {% endif %}
      </form>
    </div>
  </div>
  <div class="sections">
    <h3 class="fw-bold mt-5">Testimoni</h3>
    <hr class="line rounded-4">
    <div class="newCar">
      <div class="row justify-content-start">
        {% for testi in ratings %}
        <div class="card mb-3 shadow-sm" style="width: 15.80%; margin: 0 5px">
          <img src="{{testi.id_mobil.image1.url}}" class="card-img-top mt-3" alt="..." style="height: 170px;">
          <div class="card-body text-center">
            <div class="row d-flex justify-content-between"></div>
            <h5 class="card-title">{{ testi.id_user.username }}</h5>
            <p>
              {% with ''|center:testi.rating as range %}
              {% for i in range %}
              <label class="text-warning starate">★</label>
              {% endfor %}
              {% endwith %}
            </p>
            <p class="card-text">{{testi.contentTestimonial}}</p>
          </div>
        </div>
        {% endfor %}
        <!-- Repeat the card div for more cards as needed -->
      </div>
    </div>
  </div>
</main>

<footer class="d-flex flex-wrap justify-content-between align-items-center py-3  border-top w-100">
  <div class="col text-start" style="color: white; font-weight:700; font-size: 13px">
    <a href="" class="mb-3 mb-md-0 text-body-secondary text-decoration-none lh-1">
      <svg class="bi" width="40" height="24">
        <use xlink:href="#bootstrap" />
      </svg>
    </a>
    <span class="mb-3 mb-md-0 text-body-secondary">&copy; RentCar</span>
  </div>
  <div class="col-md-4 text-end mr-3">
    <img src="{% static 'img/wa.png' %}" alt="" width="23px">
    <img src="{% static 'img/instagram.png' %}" alt="" width="23px">
    <img src="{% static 'img/facebook.png' %}" alt="" width="23px">
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
  const carousel = document.getElementById('productCarousel');
  const dots = document.querySelectorAll('.dot');

  carousel.addEventListener('slid.bs.carousel', function (event) {
    dots.forEach((dot, index) => {
      if (index === event.to) {
        dot.classList.add('active');
      } else {
        dot.classList.remove('active');
      }
    });
  });
</script>
{% endblock contents %}

templates/user/home.html
{% extends '../base.html' %}
{% load static %}
{% block headers %}
<link href="{% static 'css/user/home.css' %}" rel="stylesheet" type="text/css">
{% endblock headers %}

{% block contents %}
{% include '../partials/navbarUser.html' %}
<main style="margin-top: 4.5%">
  {% include 'widgets/flasher.html' %}
  <div class="row">
  <!-- Hero Section -->
  <div class="hero-section rounded-4 d-flex justify-content-center align-items-center text-center flex-column">
    <div class="header"><b>WELCOME TO RENTCAR</b></div>
    <div class="subheader">Ease of Driving with Quality Vehicles!</div>
    <div class="mt-4 desc">Enjoy a comfortable and safe driving experience with our best car rental
      service. Providing various car choices for your various needs,
      from business trips to family holidays.</div>
    <a href="{% url 'mobil:listCar' %}" class="btn btn-reserved fw-medium shadow-none">Book Now</a>
  </div>

  <div class="sections">
    <h3 class="fw-bold mt-5">About Us</h3>
    <hr class="line rounded-4">
    <div class="about">
      <div class="row">
        <div class="col-md-7 d-flex justify-content-center align-items-center">
          <p style="text-indent: 45px;">RentCar Lorem ipsum dolor sit amet,
            consectetur adipiscing elit, sed do eiusmod tempor incididunt
            ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
            commodo consequat. Duis aute irure dolor in reprehenderit
            in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            Excepteur sint occaecat cupidatat non proident, sunt in culpa
            qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="col-md-5">
          <img src="{% static 'img/about.png' %}" width="500px" height="520px" alt="" class="rounded-4">
        </div>
      </div>
    </div>
  </div>

  <div class="sections">
    <h3 class="fw-bold mt-5">New Rental Car</h3>
    <hr class="line rounded-4">
    <div class="newCar">
      <div class="row justify-content-start">
        {% for mobil in mobils %}
        <!-- card -->
        <div class="card mb-3 shadow-sm" style="width: 15.80%; margin: 0 5px">
          <img src="{{mobil.image1.url}}" class="card-img-top mt-3" alt="..." style="height: 120px; ">
          <div class="card-body">
            <h5 class="card-title">{{mobil.name}}</h5>
            <p class="card-text">{{mobil.description }}</p>
            <p><b>{{mobil.pricePerDay}},- /hari</b></p>
            <a href="{% url 'mobil:detailCar' mobil_id=mobil.id %}"
              class="btn shadow-none description-button w-100">Detail</a>
          </div>
        </div>
        {% endfor %}
        <!-- Repeat the card div for more cards as needed -->
      </div>
    </div>
  </div>

  <div class="sections">
    <h3 class="fw-bold mt-5">Testimoni</h3>
    <hr class="line rounded-4">
    <div class="newCar">
      <div class="row justify-content-start">
        {% for testi in ratings %}
        <div class="card mb-3 shadow-sm" style="width: 15.80%; margin: 0 5px">
          <img src="{{testi.id_mobil.image1.url}}" class="card-img-top mt-3" alt="..." style="height: 120px; ">
          <div class="card-body text-center">
            <div class="row d-flex justify-content-between"></div>
            <h5 class="card-title">{{ testi.id_user.username}}</h5>
            <p>
              {% with ''|center:testi.rating as range %}
              {% for i in range %}
              <label class="text-warning starate">★</label>
              {% endfor %}
              {% endwith %}
            </p>
            <p class="card-text">{{testi.contentTestimonial}}</p>
          </div>
        </div>
        {% endfor %}
        <!-- Repeat the card div for more cards as needed -->
      </div>
    </div>
  </div>
</main>

<!-- Footer -->
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <div class="col-md-4 d-flex align-items-center">
    <a href="" class="mb-3 me-2  text-body-secondary text-decoration-none lh-1">
      <svg class="bi" width="40" height="24">
        <use xlink:href="#bootstrap" />
      </svg>
    </a>
    <span class="mb-3  text-body-secondary">&copy; RentCar</span>
  </div>
  <div class="col-md-4 text-end">
    <img src="{% static 'img/wa.png' %}" alt="" width="23px">
    <img src="{% static 'img/instagram.png' %}" alt="" width="23px">
    <img src="{% static 'img/facebook.png' %}" alt="" width="23px">

  </div>
</footer>
{% endblock contents %}

templates/user/pesananSaya.html
{% extends '../base.html' %}
{% load static %}
{% block headers %}
<link rel="stylesheet" href="{% static 'css/user/pesananSaya.css' %}">
{% endblock headers %}
{% block contents %}
{% include '../partials/navbarUser.html' %}

<main class="container-fluid" style="margin-top:5%">

        {% if orders %}
        <div class="row d-flex justify-content-center">
        {% include 'widgets/flasher.html' %}

        <h2 class="text-center mb-3 ">My Orders</h2>
        {% for order in orders %}
        <div class="col-md-7 mb-4 ">
            <div class="card shadow">
                <div class="cardbody">
                    <div class="header row d-flex justify-content-between ">
                        <div class="col-4 mt-1">
                            <p class="card-text">Pesanan: {{ order.id }}</p>
                            <p class="card-text">Status: {{ order.status }}</p>
                        </div>
                        <div class="col-4 text-end">
                            {% if order.payment_receipt_image_path %}
                            <button type="button" class="btn shadow-none btn-primary button-side-top mb-1" data-bs-toggle="modal" data-bs-target="#receiptModal{{ order.id }}">
                                View Payment Receipt
                            </button>

                            <!-- Modal for Payment Receipt -->
                            <div class="modal fade" id="receiptModal{{ order.id }}" tabindex="-1" aria-labelledby="receiptModalLabel{{ order.id }}" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="receiptModalLabel{{ order.id }}">Payment Receipt</h5>
                                            <button type="button" class="btn-close shadow-none" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <img src="{{ order.payment_receipt_image_path.url }}" class="img-fluid" alt="Payment Receipt">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% else %}
                            <p class="card-text">No payment receipt available.</p>
                            {% endif %}
                            {% if order.returnorder_set.last.status == "Dikembalikan" %}
                            <button type="button" class="btn shadow-none btn-danger button-side-top disabled">Kembalikan</button>
                            {% else %}
                            {% if order.status == "Belum Terkonfirmasi" %}
                            <button type="button" class="btn shadow-none btn-danger button-side-top disabled">Kembalikan</button>
                            {% elif order.status == "Terkonfirmasi" %}
                            <button type="button" class="btn shadow-none btn-danger button-side-top disabled">Kembalikan</button>
                            {% else %}
                            <button type="button" class="btn shadow-none btn-danger button-side-top" data-bs-toggle="modal" data-bs-target="#returnModal{{ order.id }}">Kembalikan</button>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row body-value d-flex justify-content-between align-items-center">
                        {% for item in order.items %}
                        <div class="col text-center">
                            <img src="{{ item.id_mobils.image1.url }}" class="card-img" alt="{{ item.id_mobils.name }}">
                        </div>
                        <div class="col text-center">
                            <div class="col header-card">{{ item.id_mobils.name }}</div>
                        </div>
                        
                        <div class="col text-center">
                            <div class="col header-card">CHECK IN</div>
                            <div class="col value-card">{{ order.start_date }}</div>
                        </div>
                        <div class="col text-center">
                            <div class="col header-card">CHECK OUT</div>
                            <div class="col value-card">{{ order.end_date }}</div>
                        </div>
                        <div class="col text-center">
                            <div class="col header-card">QUANTITY</div>
                            <div class="col value-card">{{ item.quantity }}</div>
                        </div>
                        <div class="col text-center">
                            <div class="col header-card">GRAND TOTAL</div>
                            <div class="col value-card">{{ order.grand_total }}</div>
                        </div>
                        <div class="col text-center">
                            <div class="col header-card">FINE</div>
                            <div class="col value-card">{{ order.fine }}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal for Returning the Car -->
        <div class="modal fade" id="returnModal{{ order.id }}" tabindex="-1" aria-labelledby="returnModalLabel{{ order.id }}" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="returnModalLabel{{ order.id }}">Return Car - Order ID: {{ order.id }}</h5>
                        <button type="button" class="btn-close shadow-none" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" enctype="multipart/form-data" action="{% url 'pesanan:returnOrder' id_order=order.id %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="rating" class="form-label">Rating</label>
                                <div class="d-flex justify-content-left">
                                    <div class="rating">
                                        <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
                                        <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                                        <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
                                        <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
                                        <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="testimonial" class="form-label">Testimonial</label>
                                <textarea class="form-control shadow-none" id="testimonial" name="contentTestimonial" rows="3" required></textarea>
                            </div>
                            <div class="mb-3 form-group">
                                <label for="image" class="form-label">Pembayaran Denda</label>
                                <input class="form-control shadow-none" type="file" id="image" name="image" accept="image/*" required>
                                <div class="form-text">wajib mengisi jika memiliki denda</div>
                            </div>
                            <button type="submit" class="btn shadow-none btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

                    
        </div>
        {% else %}
        <p class="text-center">You have no orders.</p>
        {% endif %}
    </main>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3  border-top w-100">
        <div class="col text-start" style="color: white; font-weight:700; font-size: 13px">
        <a href="" class="mb-3 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="40" height="24">
            <use xlink:href="#bootstrap" />
            </svg>
        </a>
        <span class="mb-3 mb-md-0 text-body-secondary">&copy; RentCar</span>
        </div>
        <div class="col-md-4 text-end mr-3">
        <img src="{% static 'img/wa.png' %}" alt="" width="23px">
        <img src="{% static 'img/instagram.png' %}" alt="" width="23px">
        <img src="{% static 'img/facebook.png' %}" alt="" width="23px">
        </div>
    </footer>

    <script>
        const ratings = document.getElementById('rating1'); const rating1 = new CDB.Rating(ratings);
        rating1.getRating;
    </script>
    {% endblock contents %}